# Generated by Django 5.2.4 on 2025-10-21 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entreestock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entreestock',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sortiestock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sortiestock',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vente',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vente',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_modifiees', to=settings.AUTH_USER_MODEL),
        ),
    ]
