# Generated by Django 5.2.4 on 2025-10-22 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_lignereception_prix_unitaire_reception_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='date_reception',
        ),
        migrations.AddField(
            model_name='reception',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
