# Generated by Django 5.2.4 on 2025-10-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_reception_date_reception_reception_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='remarque',
            field=models.TextField(blank=True, null=True),
        ),
    ]
